# -*- coding: utf-8 -*-
#!/usr/bin/env python3
# 本轮新键翻译（邀请/照片/删除账号/关系计算器/时间轴/Billing/Realtime）
import json, os

T = {
"es": {
 "inviteCodeHint":"Código de invitación (p. ej. AB12CD34)","redeem":"Unirse","memberOwner":"propietario","memberEditor":"editor","memberViewer":"espectador","inviteFailed":"No se pudo crear la invitación — ¿eres el propietario del árbol?",
 "fBurial":"Lugar de enterramiento","restoreFromBackup":"Restaurar desde copia","restoreSuccess":"Restaurado · {name}","restoreError":"No se pudo restaurar esta copia",
 "privacyPolicy":"Política de privacidad","deleteTreeTitle":"¿Eliminar este árbol?","deleteTreeBody":"«{name}» y sus {count} personas se eliminarán de este dispositivo. No se puede deshacer.",
 "personNew":"Nueva persona","addFirstPerson":"Añade a la primera persona","addFirstPersonSub":"Empieza contigo y añade parientes",
 "signInWithGoogle":"Continuar con Google","sentDone":"Enviado","sharePublicTitle":"Hacer público este homenaje","sharePublicBody":"Quien tenga el enlace verá: el nombre, las fechas, el mensaje y los homenajes. Nunca se muestran familiares vivos.","sharePublicEnable":"Activar y compartir","shareText":"En memoria · {name} ({years})\n{url}","errShare":"No se pudo compartir · inténtalo de nuevo","proPriceSub":"Menos de 1,67 $ al mes · cancela cuando quieras",
 "relationshipTitle":"Calculadora de parentesco","relationshipPickA":"Elige la primera persona","relationshipPickB":"Elige la segunda persona","relationshipCompute":"¿Qué parentesco tienen?","relSelf":"La misma persona","relSpouseOf":"{a} es pareja de {b}","relParentOf":"{a} es progenitor de {b}","relChildOf":"{a} es hijo/a de {b}","relNth":"{a} y {b} son parientes en {deg}° grado","relNoPath":"No se encontró conexión familiar","relPath":"Camino","relPathTitle":"Ruta de parentesco","relSpouses":"{a} y {b} son pareja","relDirectAncestor":"{name} está {gen, plural, one{1 generación} other{{gen} generaciones}} por encima","relDirectDescendant":"{name} está {gen, plural, one{1 generación} other{{gen} generaciones}} por debajo","relSiblings":"{a} y {b} son hermanos","relCousins":"{a} y {b} son primos en {deg}° grado","relUncleNiece":"{a} y {b} tienen relación tío/sobrino","relRelatedByMarriage":"{a} y {b} están conectados por matrimonio",
 "timelineTitle":"Cronología de vida","timelineBirth":"Nacimiento","timelineDeath":"Fallecimiento","timelineMarriage":"Matrimonio","timelineChildBorn":"Nació {name}",
 "deleteAccountDone":"Cuenta y datos en la nube eliminados","deleteAccountLocalOnly":"No has iniciado sesión — se borraron los datos locales","wipeLocalConfirm":"¿Borrar también todo lo guardado en este dispositivo?","wipeLocal":"Borrar datos locales","realtimeTribute":"{name} acaba de ofrecer un homenaje","photoUploaded":"Foto actualizada","photoPickFailed":"No se pudo procesar esta foto","proBillingUnavailable":"Google Play Billing no está disponible en esta compilación. Pro se activa tras la configuración de la tienda.","proPurchased":"¡Gracias! Lararium Pro está activo."
},
"pt": {
 "inviteCodeHint":"Código de convite (ex. AB12CD34)","redeem":"Entrar","memberOwner":"proprietário","memberEditor":"editor","memberViewer":"espectador","inviteFailed":"Não foi possível criar o convite — você é o proprietário da árvore?",
 "fBurial":"Local de sepultamento","restoreFromBackup":"Restaurar do backup","restoreSuccess":"Restaurado · {name}","restoreError":"Não foi possível restaurar este backup",
 "privacyPolicy":"Política de privacidade","deleteTreeTitle":"Excluir esta árvore?","deleteTreeBody":"“{name}” e suas {count} pessoas serão removidas deste dispositivo. Não pode ser desfeito.",
 "personNew":"Nova pessoa","addFirstPerson":"Adicione a primeira pessoa","addFirstPersonSub":"Comece por você e adicione parentes",
 "signInWithGoogle":"Continuar com o Google","sentDone":"Enviado","sharePublicTitle":"Tornar este memorial público","sharePublicBody":"Quem tiver o link verá: o nome, as datas, a mensagem e as homenagens. Parentes vivos nunca são exibidos.","sharePublicEnable":"Ativar e compartilhar","shareText":"Em memória · {name} ({years})\n{url}","errShare":"Não foi possível compartilhar · tente novamente","proPriceSub":"Menos de R$ 1,67 por mês · cancele quando quiser",
 "relationshipTitle":"Calculadora de parentesco","relationshipPickA":"Escolha a primeira pessoa","relationshipPickB":"Escolha a segunda pessoa","relationshipCompute":"Qual é o parentesco?","relSelf":"A mesma pessoa","relSpouseOf":"{a} é cônjuge de {b}","relParentOf":"{a} é pai/mãe de {b}","relChildOf":"{a} é filho/a de {b}","relNth":"{a} e {b} são parentes em {deg}º grau","relNoPath":"Nenhuma conexão familiar encontrada","relPath":"Caminho","relPathTitle":"Caminho do parentesco","relSpouses":"{a} e {b} são cônjuges","relDirectAncestor":"{name} está {gen, plural, one{1 geração} other{{gen} gerações}} acima na linha","relDirectDescendant":"{name} está {gen, plural, one{1 geração} other{{gen} gerações}} abaixo na linha","relSiblings":"{a} e {b} são irmãos","relCousins":"{a} e {b} são primos em {deg}º grau","relUncleNiece":"{a} e {b} têm relação de tio/sobrinho","relRelatedByMarriage":"{a} e {b} estão conectados por casamento",
 "timelineTitle":"Linha do tempo de vida","timelineBirth":"Nascimento","timelineDeath":"Falecimento","timelineMarriage":"Casamento","timelineChildBorn":"{name} nasceu",
 "deleteAccountDone":"Conta e dados na nuvem excluídos","deleteAccountLocalOnly":"Você não está conectado — os dados locais foram apagados","wipeLocalConfirm":"Apagar também tudo o que está guardado neste dispositivo?","wipeLocal":"Apagar dados locais","realtimeTribute":"{name} acabou de oferecer uma homenagem","photoUploaded":"Foto atualizada","photoPickFailed":"Não foi possível processar esta foto","proBillingUnavailable":"O Google Play Billing não está disponível nesta compilação. O Pro é ativado após a configuração da loja.","proPurchased":"Obrigado! O Lararium Pro está ativo."
},
"fr": {
 "inviteCodeHint":"Code d'invitation (ex. AB12CD34)","redeem":"Rejoindre","memberOwner":"propriétaire","memberEditor":"éditeur","memberViewer":"spectateur","inviteFailed":"Impossible de créer l'invitation — êtes-vous le propriétaire de l'arbre ?",
 "fBurial":"Lieu d'inhumation","restoreFromBackup":"Restaurer depuis une sauvegarde","restoreSuccess":"Restauré · {name}","restoreError":"Impossible de restaurer cette sauvegarde",
 "privacyPolicy":"Politique de confidentialité","deleteTreeTitle":"Supprimer cet arbre ?","deleteTreeBody":"« {name} » et ses {count} personnes seront supprimés de cet appareil. Action irréversible.",
 "personNew":"Nouvelle personne","addFirstPerson":"Ajoutez la première personne","addFirstPersonSub":"Commencez par vous, puis ajoutez vos proches",
 "signInWithGoogle":"Continuer avec Google","sentDone":"Envoyé","sharePublicTitle":"Rendre ce mémorial public","sharePublicBody":"Toute personne ayant le lien verra : le nom, les dates, le message et les hommages. Les proches vivants ne sont jamais montrés.","sharePublicEnable":"Activer et partager","shareText":"En mémoire · {name} ({years})\n{url}","errShare":"Partage impossible · réessayez","proPriceSub":"Moins de 1,67 € par mois · résiliable à tout moment",
 "relationshipTitle":"Calculateur de parenté","relationshipPickA":"Choisissez la première personne","relationshipPickB":"Choisissez la deuxième personne","relationshipCompute":"Quel est le lien de parenté ?","relSelf":"Même personne","relSpouseOf":"{a} est conjoint de {b}","relParentOf":"{a} est parent de {b}","relChildOf":"{a} est enfant de {b}","relNth":"{a} et {b} sont parents au {deg}° degré","relNoPath":"Aucun lien familial trouvé","relPath":"Chemin","relPathTitle":"Chemin de parenté","relSpouses":"{a} et {b} sont conjoints","relDirectAncestor":"{name} est {gen, plural, one{1 génération} other{{gen} générations}} au-dessus","relDirectDescendant":"{name} est {gen, plural, one{1 génération} other{{gen} générations}} en dessous","relSiblings":"{a} et {b} sont frères et sœurs","relCousins":"{a} et {b} sont cousins au {deg}° degré","relUncleNiece":"{a} et {b} ont un lien oncle/tante – neveu/nièce","relRelatedByMarriage":"{a} et {b} sont liés par mariage",
 "timelineTitle":"Chronologie de vie","timelineBirth":"Naissance","timelineDeath":"Décès","timelineMarriage":"Mariage","timelineChildBorn":"{name} est né(e)",
 "deleteAccountDone":"Compte et données cloud supprimés","deleteAccountLocalOnly":"Vous n'êtes pas connecté — les données locales ont été effacées","wipeLocalConfirm":"Effacer également tout ce qui est stocké sur cet appareil ?","wipeLocal":"Effacer les données locales","realtimeTribute":"{name} vient d'offrir un hommage","photoUploaded":"Photo mise à jour","photoPickFailed":"Impossible de traiter cette photo","proBillingUnavailable":"Google Play Billing n'est pas disponible sur cette version. Pro s'active après la configuration du store.","proPurchased":"Merci ! Lararium Pro est actif."
},
"de": {
 "inviteCodeHint":"Einladungscode (z. B. AB12CD34)","redeem":"Beitreten","memberOwner":"Besitzer","memberEditor":"Bearbeiter","memberViewer":"Betrachter","inviteFailed":"Einladung konnte nicht erstellt werden — bist du der Baum-Besitzer?",
 "fBurial":"Beerdigungsort","restoreFromBackup":"Aus Backup wiederherstellen","restoreSuccess":"Wiederhergestellt · {name}","restoreError":"Dieses Backup konnte nicht wiederhergestellt werden",
 "privacyPolicy":"Datenschutzerklärung","deleteTreeTitle":"Diesen Baum löschen?","deleteTreeBody":"„{name}“ und {count} Personen werden von diesem Gerät entfernt. Das kann nicht rückgängig gemacht werden.",
 "personNew":"Neue Person","addFirstPerson":"Füge die erste Person hinzu","addFirstPersonSub":"Beginne mit dir und füge Verwandte hinzu",
 "signInWithGoogle":"Mit Google fortfahren","sentDone":"Gesendet","sharePublicTitle":"Dieses Gedenken öffentlich machen","sharePublicBody":"Wer den Link hat, sieht: Namen, Lebensdaten, Gedenktext und Gaben. Lebende Angehörige werden nie gezeigt.","sharePublicEnable":"Aktivieren & teilen","shareText":"In lieber Erinnerung · {name} ({years})\n{url}","errShare":"Teilen fehlgeschlagen · bitte erneut versuchen","proPriceSub":"Weniger als 1,67 € im Monat · jederzeit kündbar",
 "relationshipTitle":"Verwandtschaftsrechner","relationshipPickA":"Wähle die erste Person","relationshipPickB":"Wähle die zweite Person","relationshipCompute":"Wie sind sie verwandt?","relSelf":"Dieselbe Person","relSpouseOf":"{a} ist Partner von {b}","relParentOf":"{a} ist Elternteil von {b}","relChildOf":"{a} ist Kind von {b}","relNth":"{a} und {b} sind {deg}° verwandt","relNoPath":"Keine familiäre Verbindung gefunden","relPath":"Pfad","relPathTitle":"Verwandtschaftspfad","relSpouses":"{a} und {b} sind Partner","relDirectAncestor":"{name} steht {gen, plural, one{1 Generation} other{{gen} Generationen}} über dir","relDirectDescendant":"{name} steht {gen, plural, one{1 Generation} other{{gen} Generationen}} unter dir","relSiblings":"{a} und {b} sind Geschwister","relCousins":"{a} und {b} sind {deg}° Cousin/Cousine","relUncleNiece":"{a} und {b} haben eine Onkel/Tante–Nichte/Neffe-Beziehung","relRelatedByMarriage":"{a} und {b} sind durch Heirat verbunden",
 "timelineTitle":"Lebenschronik","timelineBirth":"Geboren","timelineDeath":"Gestorben","timelineMarriage":"Heirat","timelineChildBorn":"{name} wurde geboren",
 "deleteAccountDone":"Konto und Cloud-Daten gelöscht","deleteAccountLocalOnly":"Du bist nicht angemeldet — lokale Daten wurden stattdessen gelöscht","wipeLocalConfirm":"Auch alles auf diesem Gerät gespeicherte löschen?","wipeLocal":"Lokale Daten löschen","realtimeTribute":"{name} hat gerade eine Gabe dargebracht","photoUploaded":"Foto aktualisiert","photoPickFailed":"Dieses Foto konnte nicht verarbeitet werden","proBillingUnavailable":"Google Play Billing ist in diesem Build nicht verfügbar. Pro wird nach der Store-Einrichtung aktiviert.","proPurchased":"Danke! Lararium Pro ist aktiv."
},
"it": {
 "inviteCodeHint":"Codice di invito (es. AB12CD34)","redeem":"Unisciti","memberOwner":"proprietario","memberEditor":"editor","memberViewer":"spettatore","inviteFailed":"Impossibile creare l'invito — sei il proprietario dell'albero?",
 "fBurial":"Luogo di sepoltura","restoreFromBackup":"Ripristina dal backup","restoreSuccess":"Ripristinato · {name}","restoreError":"Impossibile ripristinare questo backup",
 "privacyPolicy":"Informativa sulla privacy","deleteTreeTitle":"Eliminare questo albero?","deleteTreeBody":"“{name}” e le sue {count} persone saranno rimosse da questo dispositivo. Operazione irreversibile.",
 "personNew":"Nuova persona","addFirstPerson":"Aggiungi la prima persona","addFirstPersonSub":"Inizia da te, poi aggiungi i parenti",
 "signInWithGoogle":"Continua con Google","sentDone":"Inviato","sharePublicTitle":"Rendi pubblico questo ricordo","sharePublicBody":"Chi ha il link vedrà: nome, date, messaggio e omaggi. I parenti viventi non sono mai mostrati.","sharePublicEnable":"Attiva e condividi","shareText":"In memoria · {name} ({years})\n{url}","errShare":"Condivisione non riuscita · riprova","proPriceSub":"Meno di 1,67 € al mese · disdici quando vuoi",
 "relationshipTitle":"Calcolatore di parentela","relationshipPickA":"Scegli la prima persona","relationshipPickB":"Scegli la seconda persona","relationshipCompute":"Qual è il legame?","relSelf":"Stessa persona","relSpouseOf":"{a} è coniuge di {b}","relParentOf":"{a} è genitore di {b}","relChildOf":"{a} è figlio/a di {b}","relNth":"{a} e {b} sono parenti di {deg}° grado","relNoPath":"Nessun legame familiare trovato","relPath":"Percorso","relPathTitle":"Percorso di parentela","relSpouses":"{a} e {b} sono coniugi","relDirectAncestor":"{name} è {gen, plural, one{1 generazione} other{{gen} generazioni}} sopra nella linea","relDirectDescendant":"{name} è {gen, plural, one{1 generazione} other{{gen} generazioni}} sotto nella linea","relSiblings":"{a} e {b} sono fratelli/sorelle","relCousins":"{a} e {b} sono cugini di {deg}° grado","relUncleNiece":"{a} e {b} hanno un legame zio/zia – nipote","relRelatedByMarriage":"{a} e {b} sono legati da matrimonio",
 "timelineTitle":"Cronologia della vita","timelineBirth":"Nascita","timelineDeath":"Morte","timelineMarriage":"Matrimonio","timelineChildBorn":"{name} è nato/a",
 "deleteAccountDone":"Account e dati cloud eliminati","deleteAccountLocalOnly":"Non sei connesso — i dati locali sono stati cancellati","wipeLocalConfirm":"Cancellare anche tutto ciò che è memorizzato su questo dispositivo?","wipeLocal":"Cancella dati locali","realtimeTribute":"{name} ha appena offerto un omaggio","photoUploaded":"Foto aggiornata","photoPickFailed":"Impossibile elaborare questa foto","proBillingUnavailable":"Google Play Billing non è disponibile in questa build. Pro si attiva dopo la configurazione dello store.","proPurchased":"Grazie! Lararium Pro è attivo."
},
"ja": {
 "inviteCodeHint":"招待コード（例 AB12CD34）","redeem":"参加する","memberOwner":"オーナー","memberEditor":"編集者","memberViewer":"閲覧者","inviteFailed":"招待コードを作成できません — あなたがツリーのオーナーですか？",
 "fBurial":"埋葬地","restoreFromBackup":"バックアップから復元","restoreSuccess":"復元しました · {name}","restoreError":"このバックアップは復元できませんでした",
 "privacyPolicy":"プライバシーポリシー","deleteTreeTitle":"このツリーを削除しますか？","deleteTreeBody":"「{name}」と{count}人の人物がこの端末から削除されます。元に戻せません。",
 "personNew":"新しい人物","addFirstPerson":"最初の人物を追加","addFirstPersonSub":"まず自分を登録し、家族を追加していきましょう",
 "signInWithGoogle":"Google で続行","sentDone":"送信済み","sharePublicTitle":"追悼ページを公開","sharePublicBody":"リンクを知っている人なら、名前・生没年・追悼メッセージ・供物を見られます。存命のご親族は表示されません。","sharePublicEnable":"公開して共有","shareText":"追悼 · {name}（{years}）\n{url}","errShare":"共有できませんでした · もう一度お試しください","proPriceSub":"月あたり167円未満 · いつでも解約可能",
 "relationshipTitle":"続柄計算ツール","relationshipPickA":"1人目を選択","relationshipPickB":"2人目を選択","relationshipCompute":"二人の続柄は？","relSelf":"同じ人物です","relSpouseOf":"{a} は {b} の配偶者です","relParentOf":"{a} は {b} の親です","relChildOf":"{a} は {b} の子です","relNth":"{a} と {b} は {deg} 親等です","relNoPath":"家族内のつながりが見つかりません","relPath":"経路","relPathTitle":"続柄の経路","relSpouses":"{a} と {b} は配偶者です","relDirectAncestor":"{name} は {gen, plural, other{{gen} 世代}}上の直系尊属です","relDirectDescendant":"{name} は {gen, plural, other{{gen} 世代}}下の直系子孫です","relSiblings":"{a} と {b} はきょうだいです","relCousins":"{a} と {b} は {deg} いとこです","relUncleNiece":"{a} と {b} はおじ・おば／めい・おいの関係です","relRelatedByMarriage":"{a} と {b} は婚姻によるつながりです",
 "timelineTitle":"人生の年表","timelineBirth":"誕生","timelineDeath":"逝去","timelineMarriage":"結婚","timelineChildBorn":"{name} が誕生",
 "deleteAccountDone":"アカウントとクラウドデータを削除しました","deleteAccountLocalOnly":"未ログインのため — ローカルデータを削除しました","wipeLocalConfirm":"この端末に保存されたデータもすべて削除しますか？","wipeLocal":"ローカルデータを削除","realtimeTribute":"{name} が供物を捧げました","photoUploaded":"写真を更新しました","photoPickFailed":"この写真を処理できませんでした","proBillingUnavailable":"このビルドでは Google Play Billing を利用できません。ストア設定後に有効化されます。","proPurchased":"ありがとうございます！Lararium Pro が有効になりました。"
},
"ko": {
 "inviteCodeHint":"초대 코드 (예: AB12CD34)","redeem":"참여하기","memberOwner":"소유자","memberEditor":"편집자","memberViewer":"뷰어","inviteFailed":"초대 코드를 만들 수 없습니다 — 트리 소유자인가요?",
 "fBurial":"안장지","restoreFromBackup":"백업에서 복원","restoreSuccess":"복원됨 · {name}","restoreError":"이 백업은 복원할 수 없습니다",
 "privacyPolicy":"개인정보 처리방침","deleteTreeTitle":"이 트리를 삭제할까요?","deleteTreeBody":"“{name}”과 {count}명이 이 기기에서 삭제됩니다. 되돌릴 수 없습니다.",
 "personNew":"새 인물","addFirstPerson":"첫 인물 추가하기","addFirstPersonSub":"먼저 본인을 등록하고 가족을 추가해 보세요",
 "signInWithGoogle":"Google로 계속하기","sentDone":"보냄","sharePublicTitle":"추모 페이지 공개","sharePublicBody":"링크가 있는 누구나 이름·생몰년·추모 메시지·헌화를 볼 수 있습니다. 생존 가족은 표시되지 않습니다.","sharePublicEnable":"공개하고 공유","shareText":"추모 · {name}({years})\n{url}","errShare":"공유 실패 · 다시 시도해 주세요","proPriceSub":"월 2,800원 미만 · 언제든 해지 가능",
 "relationshipTitle":"촌수 계산기","relationshipPickA":"첫 번째 사람 선택","relationshipPickB":"두 번째 사람 선택","relationshipCompute":"어떤 관계인가요?","relSelf":"같은 사람입니다","relSpouseOf":"{a}은(는) {b}의 배우자입니다","relParentOf":"{a}은(는) {b}의 부모입니다","relChildOf":"{a}은(는) {b}의 자녀입니다","relNth":"{a}과(와) {b}은(는) {deg}촌입니다","relNoPath":"가족 연결을 찾을 수 없습니다","relPath":"경로","relPathTitle":"촌수 경로","relSpouses":"{a}과(와) {b}은(는) 배우자입니다","relDirectAncestor":"{name}은(는) {gen}대 위 직계尊속입니다","relDirectDescendant":"{name}은(는) {gen}대 아래 직계 자손입니다","relSiblings":"{a}과(와) {b}은(는) 형제자매입니다","relCousins":"{a}과(와) {b}은(는) {deg}촌 사촌입니다","relUncleNiece":"{a}과(와) {b}은(는) 숙모/삼촌 – 조카 관계입니다","relRelatedByMarriage":"{a}과(와) {b}은(는) 혼인으로 연결되어 있습니다",
 "timelineTitle":"삶의 연표","timelineBirth":"출생","timelineDeath":"사망","timelineMarriage":"결혼","timelineChildBorn":"{name} 출생",
 "deleteAccountDone":"계정과 클라우드 데이터가 삭제되었습니다","deleteAccountLocalOnly":"로그인되어 있지 않습니다 — 로컬 데이터를 삭제했습니다","wipeLocalConfirm":"이 기기에 저장된 모든 데이터도 삭제할까요?","wipeLocal":"로컬 데이터 삭제","realtimeTribute":"{name}님이 방금 추모를 올렸습니다","photoUploaded":"사진이 업데이트되었습니다","photoPickFailed":"이 사진을 처리할 수 없습니다","proBillingUnavailable":"이 빌드에서는 Google Play Billing을 사용할 수 없습니다. 스토어 설정 후 활성화됩니다.","proPurchased":"감사합니다! Lararium Pro가 활성화되었습니다."
},
"zh-Hans": {
 "inviteCodeHint":"邀请码（如 AB12CD34）","redeem":"加入","memberOwner":"所有者","memberEditor":"编辑者","memberViewer":"查看者","inviteFailed":"无法创建邀请——你是这棵树的所有者吗？",
 "fBurial":"安葬地","restoreFromBackup":"从备份恢复","restoreSuccess":"已恢复 · {name}","restoreError":"无法恢复此备份",
 "privacyPolicy":"隐私政策","deleteTreeTitle":"删除这棵树？","deleteTreeBody":"「{name}」及其 {count} 位人物将从本设备移除，且无法撤销。",
 "personNew":"新建人物","addFirstPerson":"添加第一位家人","addFirstPersonSub":"从自己开始，再逐位添加亲属",
 "signInWithGoogle":"使用 Google 继续","sentDone":"已送出","sharePublicTitle":"公开这页纪念","sharePublicBody":"拿到链接的人可以看到：姓名、生卒年份、纪念文字与致敬。绝不会显示在世亲属的信息。","sharePublicEnable":"开启并分享","shareText":"谨以此纪念 · {name}（{years}）\n{url}","errShare":"分享失败 · 请重试","proPriceSub":"每月不到 14 元 · 随时取消",
 "relationshipTitle":"关系计算器","relationshipPickA":"选择第一位人物","relationshipPickB":"选择第二位人物","relationshipCompute":"他们是什么关系？","relSelf":"同一个人","relSpouseOf":"{a} 是 {b} 的配偶","relParentOf":"{a} 是 {b} 的父母","relChildOf":"{a} 是 {b} 的子女","relNth":"{a} 与 {b} 相隔 {deg} 度","relNoPath":"未找到家族关联","relPath":"路径","relPathTitle":"关系路径","relSpouses":"{a} 与 {b} 是配偶","relDirectAncestor":"{name} 是上推 {gen} 代的直系尊亲属","relDirectDescendant":"{name} 是下延 {gen} 代的直系后代","relSiblings":"{a} 与 {b} 是兄弟姐妹","relCousins":"{a} 与 {b} 是 {deg} 代堂/表亲","relUncleNiece":"{a} 与 {b} 是长辈—晚辈（叔侄/姑侄）关系","relRelatedByMarriage":"{a} 与 {b} 因婚姻相连",
 "timelineTitle":"人生大事记","timelineBirth":"出生","timelineDeath":"逝世","timelineMarriage":"结婚","timelineChildBorn":"{name} 出生",
 "deleteAccountDone":"账号与云端数据已删除","deleteAccountLocalOnly":"当前未登录——已清除本机数据","wipeLocalConfirm":"同时删除本设备上保存的全部数据吗？","wipeLocal":"删除本机数据","realtimeTribute":"{name} 刚刚献上了一份致敬","photoUploaded":"照片已更新","photoPickFailed":"无法处理这张照片","proBillingUnavailable":"当前构建没有 Google Play 商店结算。商店配置完成后 Pro 即可购买。","proPurchased":"感谢支持！Lararium Pro 已激活。"
},
"zh-Hant": {
 "inviteCodeHint":"邀請碼（如 AB12CD34）","redeem":"加入","memberOwner":"擁有者","memberEditor":"編輯者","memberViewer":"檢視者","inviteFailed":"無法建立邀請——你是這棵樹的擁有者嗎？",
 "fBurial":"安葬地","restoreFromBackup":"從備份還原","restoreSuccess":"已還原 · {name}","restoreError":"無法還原此備份",
 "privacyPolicy":"隱私權政策","deleteTreeTitle":"刪除這棵樹？","deleteTreeBody":"「{name}」及其 {count} 位人物將從本裝置移除，且無法復原。",
 "personNew":"新增人物","addFirstPerson":"新增第一位家人","addFirstPersonSub":"從自己開始，再逐位新增親屬",
 "signInWithGoogle":"使用 Google 繼續","sentDone":"已送出","sharePublicTitle":"公開這頁紀念","sharePublicBody":"拿到連結的人可以看到：姓名、生卒年份、紀念文字與致敬。絕不會顯示在世親屬的資訊。","sharePublicEnable":"開啟並分享","shareText":"謹以此紀念 · {name}（{years}）\n{url}","errShare":"分享失敗 · 請重試","proPriceSub":"每月不到 NT$50 · 隨時取消",
 "relationshipTitle":"關係計算器","relationshipPickA":"選擇第一位人物","relationshipPickB":"選擇第二位人物","relationshipCompute":"他們是什麼關係？","relSelf":"同一個人","relSpouseOf":"{a} 是 {b} 的配偶","relParentOf":"{a} 是 {b} 的父母","relChildOf":"{a} 是 {b} 的子女","relNth":"{a} 與 {b} 相隔 {deg} 度","relNoPath":"未找到家族關聯","relPath":"路徑","relPathTitle":"關係路徑","relSpouses":"{a} 與 {b} 是配偶","relDirectAncestor":"{name} 是上推 {gen} 代的直系尊親屬","relDirectDescendant":"{name} 是下延 {gen} 代的直系後代","relSiblings":"{a} 與 {b} 是兄弟姊妹","relCousins":"{a} 與 {b} 是 {deg} 代堂/表親","relUncleNiece":"{a} 與 {b} 是長輩—晚輩（叔姪/姑姪）關係","relRelatedByMarriage":"{a} 與 {b} 因婚姻相連",
 "timelineTitle":"人生大事記","timelineBirth":"出生","timelineDeath":"逝世","timelineMarriage":"結婚","timelineChildBorn":"{name} 出生",
 "deleteAccountDone":"帳號與雲端資料已刪除","deleteAccountLocalOnly":"目前未登入——已清除本機資料","wipeLocalConfirm":"同時刪除本裝置上保存的全部資料嗎？","wipeLocal":"刪除本機資料","realtimeTribute":"{name} 剛剛獻上一份致敬","photoUploaded":"照片已更新","photoPickFailed":"無法處理這張照片","proBillingUnavailable":"此建置未啟用 Google Play 帳務。商店設定完成後即可購買。","proPurchased":"感謝支持！Lararium Pro 已啟用。"
},
"ru": {
 "inviteCodeHint":"Код приглашения (напр. AB12CD34)","redeem":"Присоединиться","memberOwner":"владелец","memberEditor":"редактор","memberViewer":"наблюдатель","inviteFailed":"Не удалось создать приглашение — вы владелец этого древа?",
 "fBurial":"Место захоронения","restoreFromBackup":"Восстановить из копии","restoreSuccess":"Восстановлено · {name}","restoreError":"Эту копию не удалось восстановить",
 "privacyPolicy":"Политика конфиденциальности","deleteTreeTitle":"Удалить это древо?","deleteTreeBody":"«{name}» и его {count} человек будут удалены с этого устройства. Действие необратимо.",
 "personNew":"Новый человек","addFirstPerson":"Добавьте первого человека","addFirstPersonSub":"Начните с себя и добавляйте родных",
 "signInWithGoogle":"Продолжить с Google","sentDone":"Отправлено","sharePublicTitle":"Сделать страницу памяти публичной","sharePublicBody":"У кого есть ссылка, увидят: имя, годы жизни, текст памяти и дары. Живые родственники никогда не показываются.","sharePublicEnable":"Включить и поделиться","shareText":"Вечная память · {name} ({years})\n{url}","errShare":"Не удалось поделиться · попробуйте снова","proPriceSub":"Менее 170 ₽ в месяц · отмена в любой момент",
 "relationshipTitle":"Калькулятор родства","relationshipPickA":"Выберите первого человека","relationshipPickB":"Выберите второго человека","relationshipCompute":"Какое у них родство?","relSelf":"Тот же человек","relSpouseOf":"{a} — супруг/супруга {b}","relParentOf":"{a} — родитель {b}","relChildOf":"{a} — ребёнок {b}","relNth":"{a} и {b} — родня {deg}°","relNoPath":"Родственная связь не найдена","relPath":"Путь","relPathTitle":"Путь родства","relSpouses":"{a} и {b} — супруги","relDirectAncestor":"{name} — прямой предок в {gen, plural, one{1 поколении} few{{gen} поколениях} many{{gen} поколениях} other{{gen} поколениях}}","relDirectDescendant":"{name} — прямой потомок в {gen, plural, one{1 поколении} few{{gen} поколениях} many{{gen} поколениях} other{{gen} поколениях}}","relSiblings":"{a} и {b} — братья/сёстры","relCousins":"{a} и {b} — {deg}-юродные братья/сёстры","relUncleNiece":"{a} и {b} — дядя/тётя и племянник/племянница","relRelatedByMarriage":"{a} и {b} связаны браком",
 "timelineTitle":"Хроника жизни","timelineBirth":"Рождение","timelineDeath":"Смерть","timelineMarriage":"Брак","timelineChildBorn":"Родился(лась) {name}",
 "deleteAccountDone":"Аккаунт и облачные данные удалены","deleteAccountLocalOnly":"Вы не вошли — вместо этого очищены локальные данные","wipeLocalConfirm":"Также удалить всё, что сохранено на этом устройстве?","wipeLocal":"Удалить локальные данные","realtimeTribute":"{name} только что поднёс дар","photoUploaded":"Фото обновлено","photoPickFailed":"Не удалось обработать это фото","proBillingUnavailable":"Google Play Billing недоступен в этой сборке. Pro активируется после настройки магазина.","proPurchased":"Спасибо! Lararium Pro активен."
},
"nl": {
 "inviteCodeHint":"Uitnodigingscode (bijv. AB12CD34)","redeem":"Deelnemen","memberOwner":"eigenaar","memberEditor":"bewerker","memberViewer":"kijker","inviteFailed":"Kon uitnodiging niet aanmaken — ben jij de boomeigenaar?",
 "fBurial":"Begraafplaats","restoreFromBackup":"Herstellen uit back-up","restoreSuccess":"Hersteld · {name}","restoreError":"Deze back-up kon niet worden hersteld",
 "privacyPolicy":"Privacybeleid","deleteTreeTitle":"Deze boom verwijderen?","deleteTreeBody":"‘{name}’ en de {count} personen worden van dit apparaat verwijderd. Dit kan niet ongedaan worden gemaakt.",
 "personNew":"Nieuwe persoon","addFirstPerson":"Voeg de eerste persoon toe","addFirstPersonSub":"Begin met jezelf en voeg familie toe",
 "signInWithGoogle":"Doorgaan met Google","sentDone":"Verzonden","sharePublicTitle":"Deze herdenking openbaar maken","sharePublicBody":"Wie de link heeft, ziet: naam, levensjaren, herdenkingsbericht en eerbetoon. Levende familieleden worden nooit getoond.","sharePublicEnable":"Inschakelen & delen","shareText":"Ter nagedachtenis · {name} ({years})\n{url}","errShare":"Delen mislukt · probeer opnieuw","proPriceSub":"Minder dan € 1,67 per maand · op elk moment opzegbaar",
 "relationshipTitle":"Familiebandencalculator","relationshipPickA":"Kies de eerste persoon","relationshipPickB":"Kies de tweede persoon","relationshipCompute":"Hoe zijn ze verwant?","relSelf":"Dezelfde persoon","relSpouseOf":"{a} is partner van {b}","relParentOf":"{a} is ouder van {b}","relChildOf":"{a} is kind van {b}","relNth":"{a} en {b} zijn {deg}° verwant","relNoPath":"Geen familieband gevonden","relPath":"Pad","relPathTitle":"Verwantschapspad","relSpouses":"{a} en {b} zijn partners","relDirectAncestor":"{name} staat {gen, plural, one{1 generatie} other{{gen} generaties}} hoger in de lijn","relDirectDescendant":"{name} staat {gen, plural, one{1 generatie} other{{gen} generaties}} lager in de lijn","relSiblings":"{a} en {b} zijn broer/zus","relCousins":"{a} en {b} zijn neef/nicht in de {deg}° graad","relUncleNiece":"{a} en {b} hebben een oom/tante – neef/nicht-relatie","relRelatedByMarriage":"{a} en {b} zijn door huwelijk verbonden",
 "timelineTitle":"Levenstijdlijn","timelineBirth":"Geboren","timelineDeath":"Overleden","timelineMarriage":"Huwelijk","timelineChildBorn":"{name} is geboren",
 "deleteAccountDone":"Account en cloudgegevens verwijderd","deleteAccountLocalOnly":"Je bent niet ingelogd — lokale gegevens zijn in plaats daarvan gewist","wipeLocalConfirm":"Ook alles op dit apparaat opgeslagen verwijderen?","wipeLocal":"Lokale gegevens verwijderen","realtimeTribute":"{name} bood zojuist een eerbetoon aan","photoUploaded":"Foto bijgewerkt","photoPickFailed":"Kon deze foto niet verwerken","proBillingUnavailable":"Google Play Billing is niet beschikbaar in deze build. Pro wordt actief na de store-installatie.","proPurchased":"Bedankt! Lararium Pro is actief."
},
}

files = {'es':'app_es.arb','pt':'app_pt.arb','fr':'app_fr.arb','de':'app_de.arb','it':'app_it.arb',
         'ja':'app_ja.arb','ko':'app_ko.arb','zh-Hans':'app_zh_Hans.arb','zh-Hant':'app_zh_Hant.arb',
         'ru':'app_ru.arb','nl':'app_nl.arb'}
for lang, fname in files.items():
    path = os.path.join('lib/l10n', fname)
    d = json.load(open(path))
    trans = T[lang]
    d.update(trans)
    json.dump(d, open(path, 'w'), ensure_ascii=False, indent=2)
    print(f'{fname}: +{len(trans)} (total {len(d)})')
dd = json.load(open('lib/l10n/app_zh.arb'))
dd.update(T['zh-Hans'])
json.dump(open('lib/l10n/app_zh.arb','w') and dd, open('lib/l10n/app_zh.arb','w'), ensure_ascii=False, indent=2)
print('ALL DONE')
