#!/usr/bin/env python3
# 为 11 种语言补齐本轮新键的翻译（复用原型已评审译法 + 人工翻译）
import json

T = {
"es": {
 "exportPdfPoster":"Póster PDF","exportPdfSub":"A4 / Carta / póster 2×","exportPng":"Imagen PNG","exportPngSub":"Alta resolución, hasta 4096 px",
 "exportGedcom":"GEDCOM 5.5.1","exportGedcomSub":"Ancestry, Family Tree Maker…","exportJson":"Copia completa (JSON)","exportJsonSub":"Personas, familias, homenajes",
 "tagFree":"Gratis","styleSection":"Estilo","includeLiving":"Incluir personas vivas","poster2x":"Tamaño póster (2×)","btnExport":"Exportar",
 "exportSuccess":"Exportado · {name}","exportEmpty":"Nada que exportar todavía — abre el árbol primero",
 "impResult":"Resultado","impPeople":"{count, plural, one{1 persona} other{{count} personas}}","impFamilies":"{count, plural, one{1 familia} other{{count} familias}} · {generations, plural, one{1 generación} other{{generations} generaciones}}",
 "impSkippedTags":"{count} etiquetas no compatibles omitidas","impOpenTree":"Abrir el árbol","impNewTreePrefix":"Importado",
 "treesSection":"Árboles familiares","newTree":"Nuevo árbol","duplicateTree":"Duplicar","renameTree":"Renombrar","deleteTree":"Eliminar árbol",
 "currentTag":"Actual","treeSwitched":"Cambiado a {name}","treeCreated":"Árbol creado","treeDuplicated":"Árbol duplicado","treeDeleted":"Árbol eliminado","errTreeName":"Escribe un nombre",
 "signIn":"Iniciar sesión","signUp":"Crear cuenta","email":"Correo","password":"Contraseña","passwordHint":"Al menos 6 caracteres","signOut":"Cerrar sesión",
 "authCardTitle":"Sincronización","authSignedInAs":"Sesión de {email}","authNeedAccount":"Crea una cuenta gratuita para sincronizar entre dispositivos. Tus datos siempre permanecen también en este dispositivo.",
 "authSwitchToSignUp":"¿Nuevo aquí? Crea una cuenta","authSwitchToSignIn":"¿Ya tienes cuenta? Inicia sesión",
 "syncNow":"Sincronizar ahora","allSynced":"Todo sincronizado","lastSync":"Última sincronización {time}","syncPushed":"{count} cambios subidos","syncPulled":"{count} novedades recibidas","syncError":"Fallo de sincronización · revisa tu conexión",
 "membersSection":"Miembros de la familia","copyInvite":"Copiar enlace de invitación","offlineQueueNote":"Los cambios se guardan sin conexión y se envían al volver a tener red.",
 "proFeatSync":"Sincronización y colaboradores ilimitados","proFeatSyncSub":"Plan gratuito: 1 árbol sincronizado","proFeatTribute":"Homenajes ilimitados","proFeatTributeSub":"Plan gratuito: 1 de cada al día",
 "proFeatCandle":"Vela eterna y ramos premium","proFeatCandleSub":"Fijada en la parte superior del homenaje","proFeatVoice":"Mensajes de voz y vídeo memorial","proFeatVoiceSub":"Diapositivas con música",
 "proFeatExport":"Exportaciones sin marca de agua","proFeatExportSub":"Pósters PDF, GEDCOM, copia completa","proFeatAds":"Sin anuncios","proFeatAdsSub":"El plan gratuito muestra un banner pequeño",
 "proNote":"El plan gratuito siempre mantiene flores, velas, incienso y mensajes disponibles. Pro añade más formas de recordar — nunca la capacidad de recordar.",
 "proCta":"Continuar","proBillingNote":"Google Play Billing se activa tras configurar la ficha de la tienda.","proPriceSub":"Menos de 1,67 $ al mes · cancela cuando quieras",
 "remSameDay":"El mismo día","rem1Day":"1 día","rem3Days":"3 días","rem7Days":"7 días","remFreeNote":"El recordatorio de aniversario incluye un homenaje gratuito ese día.",
 "remTitle":"Recordatorios","remAnniv":"Aniversarios de fallecimiento","remBirth":"Cumpleaños","remTime":"Recordar a las","remDays":"Días de antelación",
 "proTitle":"Lararium Pro","syncTitle":"Sincronizar","impPick":"Elegir un archivo .ged","impNote":"Se procesa en este dispositivo — nada se sube","impGo":"Iniciar importación",
 "quotaExhaustedTitle":"El homenaje de hoy está enviado","quotaExhaustedBody":"Ya ofreciste uno hoy. Mañana habrá más — y un mensaje escrito es siempre gratis.","quotaMessageFree":"Los mensajes son siempre gratis","quotaAnniversary":"Aniversario hoy · un homenaje extra incluido",
 "annivOf":"{name} · aniversario","birthdayOf":"{name} · cumpleaños","upcomingThisMonth":"Próximos","noUpcoming":"Ningún aniversario o cumpleaños en los próximos 30 días"
},
"pt": {
 "exportPdfPoster":"Pôster PDF","exportPdfSub":"A4 / Carta / pôster 2×","exportPng":"Imagem PNG","exportPngSub":"Alta resolução, até 4096 px",
 "exportGedcom":"GEDCOM 5.5.1","exportGedcomSub":"Ancestry, Family Tree Maker…","exportJson":"Backup completo (JSON)","exportJsonSub":"Pessoas, famílias, homenagens",
 "tagFree":"Grátis","styleSection":"Estilo","includeLiving":"Incluir pessoas vivas","poster2x":"Tamanho pôster (2×)","btnExport":"Exportar",
 "exportSuccess":"Exportado · {name}","exportEmpty":"Nada para exportar ainda — abra a árvore primeiro",
 "impResult":"Resultado","impPeople":"{count, plural, one{1 pessoa} other{{count} pessoas}}","impFamilies":"{count, plural, one{1 família} other{{count} famílias}} · {generations, plural, one{1 geração} other{{generations} gerações}}",
 "impSkippedTags":"{count} tags não suportadas ignoradas","impOpenTree":"Abrir a árvore","impNewTreePrefix":"Importado",
 "treesSection":"Árvores da família","newTree":"Nova árvore","duplicateTree":"Duplicar","renameTree":"Renomear","deleteTree":"Excluir árvore",
 "currentTag":"Atual","treeSwitched":"Mudou para {name}","treeCreated":"Árvore criada","treeDuplicated":"Árvore duplicada","treeDeleted":"Árvore excluída","errTreeName":"Digite um nome",
 "signIn":"Entrar","signUp":"Criar conta","email":"E-mail","password":"Senha","passwordHint":"Pelo menos 6 caracteres","signOut":"Sair",
 "authCardTitle":"Sincronização","authSignedInAs":"Conectado como {email}","authNeedAccount":"Crie uma conta gratuita para sincronizar entre dispositivos. Seus dados também ficam sempre neste dispositivo.",
 "authSwitchToSignUp":"Novo por aqui? Crie uma conta","authSwitchToSignIn":"Já tem conta? Entrar",
 "syncNow":"Sincronizar agora","allSynced":"Tudo sincronizado","lastSync":"Última sincronização {time}","syncPushed":"{count} alterações enviadas","syncPulled":"{count} novidades recebidas","syncError":"Falha na sincronização · verifique sua conexão",
 "membersSection":"Membros da família","copyInvite":"Copiar link de convite","offlineQueueNote":"As edições ficam na fila off-line e são enviadas quando você se reconectar.",
 "proFeatSync":"Sincronização e colaboradores ilimitados","proFeatSyncSub":"Plano grátis: 1 árvore sincronizada","proFeatTribute":"Homenagens ilimitadas","proFeatTributeSub":"Plano grátis: 1 de cada por dia",
 "proFeatCandle":"Vela eterna e buquês premium","proFeatCandleSub":"Fixada no topo do memorial","proFeatVoice":"Mensagens de voz e vídeo memorial","proFeatVoiceSub":"Slides com música",
 "proFeatExport":"Exportações sem marca d'água","proFeatExportSub":"Pôsteres PDF, GEDCOM, backup completo","proFeatAds":"Sem anúncios","proFeatAdsSub":"O plano grátis mostra um pequeno banner",
 "proNote":"O plano grátis mantém sempre flores, velas, incenso e mensagens disponíveis. O Pro adiciona mais formas de lembrar — nunca a capacidade de lembrar.",
 "proCta":"Continuar","proBillingNote":"O Google Play Billing é ativado após a configuração da loja.","proPriceSub":"Menos de R$ 1,67 por mês · cancele quando quiser",
 "remSameDay":"No mesmo dia","rem1Day":"1 dia","rem3Days":"3 dias","rem7Days":"7 dias","remFreeNote":"O lembrete de aniversário inclui uma homenagem gratuita nesse dia.",
 "remTitle":"Lembretes","remAnniv":"Aniversários de falecimento","remBirth":"Aniversários","remTime":"Lembrar às","remDays":"Dias de antecedência",
 "proTitle":"Lararium Pro","syncTitle":"Sincronizar","impPick":"Escolher um arquivo .ged","impNote":"Processado neste dispositivo — nada é enviado","impGo":"Iniciar importação",
 "quotaExhaustedTitle":"A homenagem de hoje foi enviada","quotaExhaustedBody":"Você já ofereceu uma hoje. Amanhã haverá mais — e uma mensagem escrita é sempre grátis.","quotaMessageFree":"As mensagens são sempre grátis","quotaAnniversary":"Aniversário hoje · uma homenagem extra incluída",
 "annivOf":"{name} · aniversário de falecimento","birthdayOf":"{name} · aniversário","upcomingThisMonth":"Próximos","noUpcoming":"Nenhum aniversário nos próximos 30 dias"
},
"fr": {
 "exportPdfPoster":"Affiche PDF","exportPdfSub":"A4 / Letter / affiche 2×","exportPng":"Image PNG","exportPngSub":"Haute résolution, jusqu'à 4096 px",
 "exportGedcom":"GEDCOM 5.5.1","exportGedcomSub":"Ancestry, Family Tree Maker…","exportJson":"Sauvegarde complète (JSON)","exportJsonSub":"Personnes, familles, hommages",
 "tagFree":"Gratuit","styleSection":"Style","includeLiving":"Inclure les personnes vivantes","poster2x":"Format affiche (2×)","btnExport":"Exporter",
 "exportSuccess":"Exporté · {name}","exportEmpty":"Rien à exporter pour l'instant — ouvrez l'arbre d'abord",
 "impResult":"Résultat","impPeople":"{count, plural, one{1 personne} other{{count} personnes}}","impFamilies":"{count, plural, one{1 famille} other{{count} familles}} · {generations, plural, one{1 génération} other{{generations} générations}}",
 "impSkippedTags":"{count} balises non prises en charge ignorées","impOpenTree":"Ouvrir l'arbre","impNewTreePrefix":"Importé",
 "treesSection":"Arbres familiaux","newTree":"Nouvel arbre","duplicateTree":"Dupliquer","renameTree":"Renommer","deleteTree":"Supprimer l'arbre",
 "currentTag":"Actuel","treeSwitched":"Passé à {name}","treeCreated":"Arbre créé","treeDuplicated":"Arbre dupliqué","treeDeleted":"Arbre supprimé","errTreeName":"Saisissez un nom",
 "signIn":"Se connecter","signUp":"Créer un compte","email":"E-mail","password":"Mot de passe","passwordHint":"Au moins 6 caractères","signOut":"Se déconnecter",
 "authCardTitle":"Synchronisation","authSignedInAs":"Connecté : {email}","authNeedAccount":"Créez un compte gratuit pour synchroniser vos appareils. Vos données restent aussi toujours sur cet appareil.",
 "authSwitchToSignUp":"Nouveau ici ? Créez un compte","authSwitchToSignIn":"Déjà un compte ? Se connecter",
 "syncNow":"Synchroniser","allSynced":"Tout est synchronisé","lastSync":"Dernière synchro {time}","syncPushed":"{count} modifications envoyées","syncPulled":"{count} mises à jour reçues","syncError":"Échec de la synchronisation · vérifiez la connexion",
 "membersSection":"Membres de la famille","copyInvite":"Copier le lien d'invitation","offlineQueueNote":"Les modifications patientent hors ligne et partent au retour du réseau.",
 "proFeatSync":"Synchro et collaborateurs illimités","proFeatSyncSub":"Plan gratuit : 1 arbre synchronisé","proFeatTribute":"Hommages illimités","proFeatTributeSub":"Plan gratuit : 1 de chaque par jour",
 "proFeatCandle":"Bougie éternelle et bouquets premium","proFeatCandleSub":"Épinglée en haut du mémorial","proFeatVoice":"Messages vocaux et vidéo commémorative","proFeatVoiceSub":"Diaporama avec musique",
 "proFeatExport":"Exports sans filigrane","proFeatExportSub":"Affiches PDF, GEDCOM, sauvegarde complète","proFeatAds":"Sans publicité","proFeatAdsSub":"Le plan gratuit affiche une petite bannière",
 "proNote":"Le plan gratuit garde toujours fleurs, bougies, encens et messages disponibles. Pro ajoute des façons de se souvenir — jamais la capacité de se souvenir.",
 "proCta":"Continuer","proBillingNote":"Google Play Billing s'activera après la configuration de la fiche store.","proPriceSub":"Moins de 1,67 € par mois · résiliable à tout moment",
 "remSameDay":"Le jour même","rem1Day":"1 jour","rem3Days":"3 jours","rem7Days":"7 jours","remFreeNote":"Le rappel d'anniversaire inclut un hommage gratuit ce jour-là.",
 "remTitle":"Rappels","remAnniv":"Anniversaires de décès","remBirth":"Anniversaires","remTime":"Rappeler à","remDays":"Jours à l'avance",
 "proTitle":"Lararium Pro","syncTitle":"Synchronisation","impPick":"Choisir un fichier .ged","impNote":"Traitement sur cet appareil — rien n'est envoyé","impGo":"Lancer l'import",
 "quotaExhaustedTitle":"L'hommage du jour est envoyé","quotaExhaustedBody":"Vous en avez déjà offert un aujourd'hui. Demain il y en aura plus — et un message écrit est toujours gratuit.","quotaMessageFree":"Les messages sont toujours gratuits","quotaAnniversary":"Anniversaire aujourd'hui · un hommage en plus inclus",
 "annivOf":"{name} · anniversaire de décès","birthdayOf":"{name} · anniversaire","upcomingThisMonth":"À venir","noUpcoming":"Aucun anniversaire dans les 30 prochains jours"
},
"de": {
 "exportPdfPoster":"PDF-Poster","exportPdfSub":"A4 / Letter / 2×-Poster","exportPng":"PNG-Bild","exportPngSub":"Hohe Auflösung, bis 4096 px",
 "exportGedcom":"GEDCOM 5.5.1","exportGedcomSub":"Ancestry, Family Tree Maker…","exportJson":"Vollbackup (JSON)","exportJsonSub":"Personen, Familien, Gedenken",
 "tagFree":"Gratis","styleSection":"Stil","includeLiving":"Lebende Personen einschließen","poster2x":"Posterformat (2×)","btnExport":"Exportieren",
 "exportSuccess":"Exportiert · {name}","exportEmpty":"Noch nichts zu exportieren — öffne zuerst den Baum",
 "impResult":"Ergebnis","impPeople":"{count, plural, one{1 Person} other{{count} Personen}}","impFamilies":"{count, plural, one{1 Familie} other{{count} Familien}} · {generations, plural, one{1 Generation} other{{generations} Generationen}}",
 "impSkippedTags":"{count} nicht unterstützte Tags übersprungen","impOpenTree":"Baum öffnen","impNewTreePrefix":"Importiert",
 "treesSection":"Stammbäume","newTree":"Neuer Baum","duplicateTree":"Duplizieren","renameTree":"Umbenennen","deleteTree":"Baum löschen",
 "currentTag":"Aktuell","treeSwitched":"Gewechselt zu {name}","treeCreated":"Baum erstellt","treeDuplicated":"Baum dupliziert","treeDeleted":"Baum gelöscht","errTreeName":"Namen eingeben",
 "signIn":"Anmelden","signUp":"Konto erstellen","email":"E-Mail","password":"Passwort","passwordHint":"Mindestens 6 Zeichen","signOut":"Abmelden",
 "authCardTitle":"Synchronisieren","authSignedInAs":"Angemeldet als {email}","authNeedAccount":"Erstelle ein kostenloses Konto für geräteübergreifende Synchronisierung. Deine Daten bleiben auch immer auf diesem Gerät.",
 "authSwitchToSignUp":"Neu hier? Konto erstellen","authSwitchToSignIn":"Schon ein Konto? Anmelden",
 "syncNow":"Jetzt synchronisieren","allSynced":"Alles synchronisiert","lastSync":"Letzte Sync {time}","syncPushed":"{count} Änderungen hochgeladen","syncPulled":"{count} Updates erhalten","syncError":"Synchronisierung fehlgeschlagen · Verbindung prüfen",
 "membersSection":"Familienmitglieder","copyInvite":"Einladungslink kopieren","offlineQueueNote":"Änderungen werden offline gepuffert und beim erneuten Verbinden gesendet.",
 "proFeatSync":"Unbegrenzte Sync & Mitwirkende","proFeatSyncSub":"Gratisplan: 1 synchronisierter Baum","proFeatTribute":"Unbegrenzte Gaben","proFeatTributeSub":"Gratisplan: 1 pro Tag und Art",
 "proFeatCandle":"Ewige Kerze & Premiumsträuße","proFeatCandleSub":"Oben am Gedenkblatt angeheftet","proFeatVoice":"Sprachnachrichten & Gedenkvideo","proFeatVoiceSub":"Fotoshow mit Musik",
 "proFeatExport":"Exporte ohne Wasserzeichen","proFeatExportSub":"PDF-Poster, GEDCOM, Vollbackup","proFeatAds":"Werbung entfernen","proFeatAdsSub":"Der Gratisplan zeigt ein kleines Banner",
 "proNote":"Der Gratisplan behält immer Blumen, Kerzen, Weihrauch und Nachrichten bei. Pro fügt mehr Arten des Erinnerns hinzu — nie die Fähigkeit zu erinnern.",
 "proCta":"Weiter","proBillingNote":"Google Play Billing wird nach der Store-Einrichtung aktiviert.","proPriceSub":"Weniger als 1,67 € im Monat · jederzeit kündbar",
 "remSameDay":"Am selben Tag","rem1Day":"1 Tag","rem3Days":"3 Tage","rem7Days":"7 Tage","remFreeNote":"Die Jahrestagserinnerung enthält an dem Tag eine kostenlose Gabe.",
 "remTitle":"Erinnerungen","remAnniv":"Todestage","remBirth":"Geburtstage","remTime":"Erinnern um","remDays":"Tage vorher",
 "proTitle":"Lararium Pro","syncTitle":"Synchronisieren","impPick":".ged-Datei wählen","impNote":"Verarbeitung auf diesem Gerät — nichts wird hochgeladen","impGo":"Import starten",
 "quotaExhaustedTitle":"Die heutige Gabe ist gesendet","quotaExhaustedBody":"Du hast heute schon eine dargebracht. Morgen gibt es mehr — und eine schriftliche Nachricht ist immer gratis.","quotaMessageFree":"Nachrichten sind immer gratis","quotaAnniversary":"Jahrestag heute · eine Extra-Gabe enthalten",
 "annivOf":"{name} · Todestag","birthdayOf":"{name} · Geburtstag","upcomingThisMonth":"Anstehend","noUpcoming":"Keine Jahrestage oder Geburtstage in den nächsten 30 Tagen"
},
"it": {
 "exportPdfPoster":"Poster PDF","exportPdfSub":"A4 / Letter / poster 2×","exportPng":"Immagine PNG","exportPngSub":"Alta risoluzione, fino a 4096 px",
 "exportGedcom":"GEDCOM 5.5.1","exportGedcomSub":"Ancestry, Family Tree Maker…","exportJson":"Backup completo (JSON)","exportJsonSub":"Persone, famiglie, omaggi",
 "tagFree":"Gratis","styleSection":"Stile","includeLiving":"Includi persone viventi","poster2x":"Formato poster (2×)","btnExport":"Esporta",
 "exportSuccess":"Esportato · {name}","exportEmpty":"Niente da esportare ancora — apri prima l'albero",
 "impResult":"Risultato","impPeople":"{count, plural, one{1 persona} other{{count} persone}}","impFamilies":"{count, plural, one{1 famiglia} other{{count} famiglie}} · {generations, plural, one{1 generazione} other{{generations} generazioni}}",
 "impSkippedTags":"{count} tag non supportati ignorati","impOpenTree":"Apri l'albero","impNewTreePrefix":"Importato",
 "treesSection":"Alberi della famiglia","newTree":"Nuovo albero","duplicateTree":"Duplica","renameTree":"Rinomina","deleteTree":"Elimina albero",
 "currentTag":"Attuale","treeSwitched":"Passato a {name}","treeCreated":"Albero creato","treeDuplicated":"Albero duplicato","treeDeleted":"Albero eliminato","errTreeName":"Inserisci un nome",
 "signIn":"Accedi","signUp":"Crea account","email":"E-mail","password":"Password","passwordHint":"Almeno 6 caratteri","signOut":"Esci",
 "authCardTitle":"Sincronizzazione","authSignedInAs":"Accesso come {email}","authNeedAccount":"Crea un account gratuito per sincronizzare tra dispositivi. I tuoi dati restano comunque sempre su questo dispositivo.",
 "authSwitchToSignUp":"Nuovo qui? Crea un account","authSwitchToSignIn":"Hai già un account? Accedi",
 "syncNow":"Sincronizza ora","allSynced":"Tutto sincronizzato","lastSync":"Ultima sincronizzazione {time}","syncPushed":"{count} modifiche inviate","syncPulled":"{count} aggiornamenti ricevuti","syncError":"Sincronizzazione non riuscita · verifica la connessione",
 "membersSection":"Membri della famiglia","copyInvite":"Copia link di invito","offlineQueueNote":"Le modifiche restano in coda offline e partono al ritorno della rete.",
 "proFeatSync":"Sincronizzazione e collaboratori illimitati","proFeatSyncSub":"Piano gratuito: 1 albero sincronizzato","proFeatTribute":"Omaggi illimitati","proFeatTributeSub":"Piano gratuito: 1 al giorno per tipo",
 "proFeatCandle":"Candela eterna e bouquet premium","proFeatCandleSub":"In alto nella pagina commemorativa","proFeatVoice":"Messaggi vocali e video commemorativo","proFeatVoiceSub":"Slideshow con musica",
 "proFeatExport":"Esportazioni senza filigrana","proFeatExportSub":"Poster PDF, GEDCOM, backup completo","proFeatAds":"Rimuovi pubblicità","proFeatAdsSub":"Il piano gratuito mostra un piccolo banner",
 "proNote":"Il piano gratuito mantiene sempre disponibili fiori, candele, incenso e messaggi. Pro aggiunge altri modi di ricordare — mai la possibilità di ricordare.",
 "proCta":"Continua","proBillingNote":"Google Play Billing si attiva dopo la configurazione dello store.","proPriceSub":"Meno di 1,67 € al mese · disdici quando vuoi",
 "remSameDay":"Stesso giorno","rem1Day":"1 giorno","rem3Days":"3 giorni","rem7Days":"7 giorni","remFreeNote":"Il promemoria dell'anniversario include un omaggio gratuito quel giorno.",
 "remTitle":"Promemoria","remAnniv":"Anniversari di morte","remBirth":"Compleanni","remTime":"Ricorda alle","remDays":"Giorni prima",
 "proTitle":"Lararium Pro","syncTitle":"Sincronizza","impPick":"Scegli un file .ged","impNote":"Elaborato su questo dispositivo — nessun caricamento","impGo":"Avvia importazione",
 "quotaExhaustedTitle":"L'omaggio di oggi è inviato","quotaExhaustedBody":"Ne hai già offerto uno oggi. Domana ce ne saranno altri — e un messaggio scritto è sempre gratuito.","quotaMessageFree":"I messaggi sono sempre gratuiti","quotaAnniversary":"Anniversario oggi · un omaggio extra incluso",
 "annivOf":"{name} · anniversario di morte","birthdayOf":"{name} · compleanno","upcomingThisMonth":"In arrivo","noUpcoming":"Nessun anniversario o compleanno nei prossimi 30 giorni"
},
"ja": {
 "exportPdfPoster":"PDFポスター","exportPdfSub":"A4 / レター / 2×ポスター","exportPng":"PNG画像","exportPngSub":"高解像度 最大4096px",
 "exportGedcom":"GEDCOM 5.5.1","exportGedcomSub":"Ancestry・Family Tree Maker 等","exportJson":"完全バックアップ（JSON）","exportJsonSub":"人物・家族・追悼",
 "tagFree":"無料","styleSection":"スタイル","includeLiving":"存命の方を含める","poster2x":"ポスターサイズ（2×）","btnExport":"書き出す",
 "exportSuccess":"書き出しました · {name}","exportEmpty":"まだ書き出すものがありません — 先にツリーを開いてください",
 "impResult":"結果","impPeople":"{count, plural, other{{count} 人}}","impFamilies":"{count, plural, other{{count} 家族}} · {generations, plural, other{{generations} 世代}}",
 "impSkippedTags":"未対応タグ {count} 件をスキップ","impOpenTree":"ツリーを開く","impNewTreePrefix":"取り込み",
 "treesSection":"家系図","newTree":"新しい家系図","duplicateTree":"複製","renameTree":"名前を変更","deleteTree":"家系図を削除",
 "currentTag":"使用中","treeSwitched":"{name} に切り替えました","treeCreated":"家系図を作成しました","treeDuplicated":"家系図を複製しました","treeDeleted":"家系図を削除しました","errTreeName":"名前を入力してください",
 "signIn":"ログイン","signUp":"アカウント作成","email":"メールアドレス","password":"パスワード","passwordHint":"6文字以上","signOut":"ログアウト",
 "authCardTitle":"同期","authSignedInAs":"{email} でログイン中","authNeedAccount":"無料アカウントで端末間同期。データは常にこの端末にも残ります。",
 "authSwitchToSignUp":"はじめての方は アカウント作成","authSwitchToSignIn":"アカウントをお持ちですか？ ログイン",
 "syncNow":"今すぐ同期","allSynced":"すべて同期済み","lastSync":"最終同期 {time}","syncPushed":"{count} 件の変更をアップロード","syncPulled":"{count} 件の更新を受信","syncError":"同期に失敗しました · 接続を確認してください",
 "membersSection":"家族メンバー","copyInvite":"招待リンクをコピー","offlineQueueNote":"オフライン中の変更はキューに保存され、再接続時に送信されます。",
 "proFeatSync":"同期と共同編集が無制限","proFeatSyncSub":"無料プラン：同期は1家系図まで","proFeatTribute":"供物が無制限","proFeatTributeSub":"無料プラン：各1日1回",
 "proFeatCandle":"永遠のろうそくとプレミアム花束","proFeatCandleSub":"追悼ページの上部に固定","proFeatVoice":"音声メッセージと追悼動画","proFeatVoiceSub":"音楽付きスライドショー",
 "proFeatExport":"透かしなしの書き出し","proFeatExportSub":"PDFポスター・GEDCOM・完全バックアップ","proFeatAds":"広告を削除","proFeatAdsSub":"無料プランでは小さなバナーを表示",
 "proNote":"無料プランでも花・ろうそく・線香・メッセージは常に使えます。Proは追悼の方法を増やすもので、追悼する力を売るものではありません。",
 "proCta":"続ける","proBillingNote":"Google Play Billing はストア公開後に有効になります。","proPriceSub":"月あたり167円未満 · いつでも解約可能",
 "remSameDay":"当日","rem1Day":"1日前","rem3Days":"3日前","rem7Days":"7日前","remFreeNote":"命日のリマインダーには当日、無料の供物が1つ含まれます。",
 "remTitle":"リマインダー","remAnniv":"命日","remBirth":"誕生日","remTime":"通知時刻","remDays":"日前に通知",
 "proTitle":"Lararium Pro","syncTitle":"同期","impPick":".gedファイルを選択","impNote":"端末内で処理します — アップロードされません","impGo":"読み込み開始",
 "quotaExhaustedTitle":"今日の供物は送信済みです","quotaExhaustedBody":"今日はすでに捧げました。明日またお供えできます — メッセージはいつでも無料です。","quotaMessageFree":"メッセージはいつでも無料","quotaAnniversary":"命日 · 今日は供物がもう1回含まれます",
 "annivOf":"{name} · 命日","birthdayOf":"{name} · 誕生日","upcomingThisMonth":"今後の予定","noUpcoming":"今後30日以内の命日・誕生日はありません"
},
"ko": {
 "exportPdfPoster":"PDF 포스터","exportPdfSub":"A4 / Letter / 2× 포스터","exportPng":"PNG 이미지","exportPngSub":"고해상도 최대 4096px",
 "exportGedcom":"GEDCOM 5.5.1","exportGedcomSub":"Ancestry, Family Tree Maker 등","exportJson":"전체 백업(JSON)","exportJsonSub":"인물 · 가족 · 추모",
 "tagFree":"무료","styleSection":"스타일","includeLiving":"생존 인물 포함","poster2x":"포스터 크기(2×)","btnExport":"내보내기",
 "exportSuccess":"내보냄 · {name}","exportEmpty":"아직 내보낼 것이 없습니다 — 먼저 트리를 열어 주세요",
 "impResult":"결과","impPeople":"{count, plural, other{{count}명}}","impFamilies":"{count, plural, other{{count}개 가족}} · {generations, plural, other{{generations}대}}",
 "impSkippedTags":"지원하지 않는 태그 {count}개 건너뜀","impOpenTree":"트리 열기","impNewTreePrefix":"가져옴",
 "treesSection":"가족 트리","newTree":"새 트리","duplicateTree":"복제","renameTree":"이름 변경","deleteTree":"트리 삭제",
 "currentTag":"사용 중","treeSwitched":"{name}(으)로 전환됨","treeCreated":"트리가 생성되었습니다","treeDuplicated":"트리가 복제되었습니다","treeDeleted":"트리가 삭제되었습니다","errTreeName":"이름을 입력하세요",
 "signIn":"로그인","signUp":"계정 만들기","email":"이메일","password":"비밀번호","passwordHint":"6자 이상","signOut":"로그아웃",
 "authCardTitle":"동기화","authSignedInAs":"{email}로 로그인됨","authNeedAccount":"무료 계정으로 기기 간 동기화하세요. 데이터는 항상 이 기기에도 남습니다.",
 "authSwitchToSignUp":"처음이신가요? 계정 만들기","authSwitchToSignIn":"계정이 있나요? 로그인",
 "syncNow":"지금 동기화","allSynced":"모두 동기화됨","lastSync":"마지막 동기화 {time}","syncPushed":"{count}개 변경 사항 업로드","syncPulled":"{count}개 업데이트 수신","syncError":"동기화 실패 · 연결을 확인하세요",
 "membersSection":"가족 구성원","copyInvite":"초대 링크 복사","offlineQueueNote":"오프라인 중 편집은 대기열에 저장되고 다시 연결되면 전송됩니다.",
 "proFeatSync":"무제한 동기화 및 공동 작업","proFeatSyncSub":"무료 플랜: 동기화 트리 1개","proFeatTribute":"무제한 추모","proFeatTributeSub":"무료 플랜: 각 1일 1회",
 "proFeatCandle":"영원한 촛불 & 프리미엄 꽃다발","proFeatCandleSub":"추모 페이지 상단에 고정","proFeatVoice":"음성 메시지 & 추모 영상","proFeatVoiceSub":"음악이 함께하는 슬라이드쇼",
 "proFeatExport":"워터마크 없는 내보내기","proFeatExportSub":"PDF 포스터 · GEDCOM · 전체 백업","proFeatAds":"광고 제거","proFeatAdsSub":"무료 플랜에는 작은 배너가 표시됩니다",
 "proNote":"무료 플랜에서도 꽃·촛불·향·메시지는 항상 유지됩니다. Pro는 추모하는 방법을 늘릴 뿐, 추모할 권리를 파는 것이 아닙니다.",
 "proCta":"계속","proBillingNote":"Google Play Billing은 스토어 등록 후 활성화됩니다.","proPriceSub":"월 2,800원 미만 · 언제든 해지 가능",
 "remSameDay":"당일","rem1Day":"1일 전","rem3Days":"3일 전","rem7Days":"7일 전","remFreeNote":"기일 알림에는 당일 무료 추모 1회가 포함됩니다.",
 "remTitle":"알림","remAnniv":"기일","remBirth":"생일","remTime":"알림 시간","remDays":"일 전",
 "proTitle":"Lararium Pro","syncTitle":"동기화","impPick":".ged 파일 선택","impNote":"기기에서 처리됩니다 — 업로드되지 않습니다","impGo":"가져오기 시작",
 "quotaExhaustedTitle":"오늘의 추모를 보냈습니다","quotaExhaustedBody":"오늘은 이미 올렸습니다. 내일 또 올 수 있고 — 글로 남기는 메시지는 언제나 무료입니다.","quotaMessageFree":"메시지는 언제나 무료","quotaAnniversary":"기일 · 오늘은 추모가 1회 더 포함됩니다",
 "annivOf":"{name} · 기일","birthdayOf":"{name} · 생일","upcomingThisMonth":"다가오는 일정","noUpcoming":"향후 30일 내 기일이나 생일이 없습니다"
},
"zh-Hans": {
 "exportPdfPoster":"PDF 海报","exportPdfSub":"A4 / Letter / 2× 海报","exportPng":"PNG 图片","exportPngSub":"高分辨率，最高 4096 px",
 "exportGedcom":"GEDCOM 5.5.1","exportGedcomSub":"Ancestry、Family Tree Maker…","exportJson":"完整备份（JSON）","exportJsonSub":"人物 · 家庭 · 纪念",
 "tagFree":"免费","styleSection":"样式","includeLiving":"包含在世人物","poster2x":"海报尺寸（2×）","btnExport":"导出",
 "exportSuccess":"已导出 · {name}","exportEmpty":"还没有可导出的内容 — 请先打开家族树",
 "impResult":"结果","impPeople":"{count, plural, other{{count} 位人物}}","impFamilies":"{count, plural, other{{count} 个家庭}} · {generations, plural, other{{generations} 代}}",
 "impSkippedTags":"跳过 {count} 个不支持的标签","impOpenTree":"打开这棵树","impNewTreePrefix":"导入",
 "treesSection":"家族树","newTree":"新建家族树","duplicateTree":"复制","renameTree":"重命名","deleteTree":"删除家族树",
 "currentTag":"当前","treeSwitched":"已切换到 {name}","treeCreated":"家族树已创建","treeDuplicated":"家族树已复制","treeDeleted":"家族树已删除","errTreeName":"请输入名称",
 "signIn":"登录","signUp":"注册","email":"邮箱","password":"密码","passwordHint":"至少 6 个字符","signOut":"退出登录",
 "authCardTitle":"同步","authSignedInAs":"已登录：{email}","authNeedAccount":"创建免费账号即可多设备同步。你的数据也始终保留在本机。",
 "authSwitchToSignUp":"第一次用？创建账号","authSwitchToSignIn":"已有账号？登录",
 "syncNow":"立即同步","allSynced":"全部已同步","lastSync":"上次同步 {time}","syncPushed":"已上传 {count} 项更改","syncPulled":"已收到 {count} 项更新","syncError":"同步失败 · 请检查网络",
 "membersSection":"家庭成员","copyInvite":"复制邀请链接","offlineQueueNote":"离线时的修改会先排队，恢复联网后自动发送。",
 "proFeatSync":"无限同步与协作","proFeatSyncSub":"免费版：1 棵同步树","proFeatTribute":"无限致敬","proFeatTributeSub":"免费版：每类每天 1 次",
 "proFeatCandle":"长明烛与高级花束","proFeatCandleSub":"置顶在纪念页顶部","proFeatVoice":"语音留言与纪念视频","proFeatVoiceSub":"配乐照片幻灯片",
 "proFeatExport":"无水印导出","proFeatExportSub":"PDF 海报 · GEDCOM · 完整备份","proFeatAds":"去除广告","proFeatAdsSub":"免费版展示小幅横幅",
 "proNote":"免费版永远保留献花、点烛、上香与留言。Pro 只是增加更多纪念方式 —— 绝不出售纪念的能力。",
 "proCta":"继续","proBillingNote":"Google Play 订阅将在商店配置完成后启用。","proPriceSub":"每月不到 14 元 · 随时取消",
 "remSameDay":"当天","rem1Day":"提前 1 天","rem3Days":"提前 3 天","rem7Days":"提前 7 天","remFreeNote":"忌日提醒当天包含一次免费致敬。",
 "remTitle":"提醒","remAnniv":"忌日","remBirth":"生日","remTime":"提醒时间","remDays":"提前天数",
 "proTitle":"Lararium Pro","syncTitle":"同步","impPick":"选择 .ged 文件","impNote":"在本机解析，不会上传","impGo":"开始导入",
 "quotaExhaustedTitle":"今天的心意已送出","quotaExhaustedBody":"今天已经献过一次了。明天再来 —— 写一段话永远是免费的。","quotaMessageFree":"留言永远免费","quotaAnniversary":"今天是忌日 · 额外包含一次致敬",
 "annivOf":"{name} · 忌日","birthdayOf":"{name} · 生日","upcomingThisMonth":"即将到来","noUpcoming":"未来 30 天没有忌日或生日"
},
"zh-Hant": {
 "exportPdfPoster":"PDF 海報","exportPdfSub":"A4 / Letter / 2× 海報","exportPng":"PNG 圖片","exportPngSub":"高解析度，最高 4096 px",
 "exportGedcom":"GEDCOM 5.5.1","exportGedcomSub":"Ancestry、Family Tree Maker…","exportJson":"完整備份（JSON）","exportJsonSub":"人物 · 家庭 · 紀念",
 "tagFree":"免費","styleSection":"樣式","includeLiving":"包含在世人物","poster2x":"海報尺寸（2×）","btnExport":"匯出",
 "exportSuccess":"已匯出 · {name}","exportEmpty":"還沒有可匯出的內容 — 請先開啟家族樹",
 "impResult":"結果","impPeople":"{count, plural, other{{count} 位人物}}","impFamilies":"{count, plural, other{{count} 個家庭}} · {generations, plural, other{{generations} 代}}",
 "impSkippedTags":"略過 {count} 個不支援的標籤","impOpenTree":"開啟這棵樹","impNewTreePrefix":"匯入",
 "treesSection":"家族樹","newTree":"新增家族樹","duplicateTree":"複製","renameTree":"重新命名","deleteTree":"刪除家族樹",
 "currentTag":"目前","treeSwitched":"已切換到 {name}","treeCreated":"家族樹已建立","treeDuplicated":"家族樹已複製","treeDeleted":"家族樹已刪除","errTreeName":"請輸入名稱",
 "signIn":"登入","signUp":"註冊","email":"電子郵件","password":"密碼","passwordHint":"至少 6 個字元","signOut":"登出",
 "authCardTitle":"同步","authSignedInAs":"已登入：{email}","authNeedAccount":"建立免費帳號即可多裝置同步。你的資料也始終保留在本機。",
 "authSwitchToSignUp":"第一次用？建立帳號","authSwitchToSignIn":"已有帳號？登入",
 "syncNow":"立即同步","allSynced":"全部已同步","lastSync":"上次同步 {time}","syncPushed":"已上傳 {count} 項變更","syncPulled":"已收到 {count} 項更新","syncError":"同步失敗 · 請檢查網路",
 "membersSection":"家庭成員","copyInvite":"複製邀請連結","offlineQueueNote":"離線時的變更會先排隊，恢復連線後自動傳送。",
 "proFeatSync":"無限同步與協作","proFeatSyncSub":"免費版：1 棵同步樹","proFeatTribute":"無限致敬","proFeatTributeSub":"免費版：每類每天 1 次",
 "proFeatCandle":"長明燭與高級花束","proFeatCandleSub":"置頂在紀念頁頂部","proFeatVoice":"語音留言與紀念影片","proFeatVoiceSub":"配樂照片幻燈片",
 "proFeatExport":"無浮水印匯出","proFeatExportSub":"PDF 海報 · GEDCOM · 完整備份","proFeatAds":"移除廣告","proFeatAdsSub":"免費版顯示小幅橫幅",
 "proNote":"免費版永遠保留獻花、點燭、上香與留言。Pro 只是增加更多紀念方式 —— 絕不出售紀念的能力。",
 "proCta":"繼續","proBillingNote":"Google Play 訂閱將在商店設定完成後啟用。","proPriceSub":"每月不到 NT$50 · 隨時取消",
 "remSameDay":"當天","rem1Day":"提前 1 天","rem3Days":"提前 3 天","rem7Days":"提前 7 天","remFreeNote":"忌日提醒當天包含一次免費致敬。",
 "remTitle":"提醒","remAnniv":"忌日","remBirth":"生日","remTime":"提醒時間","remDays":"提前天數",
 "proTitle":"Lararium Pro","syncTitle":"同步","impPick":"選擇 .ged 檔案","impNote":"在本機解析，不會上傳","impGo":"開始匯入",
 "quotaExhaustedTitle":"今天的心意已送出","quotaExhaustedBody":"今天已經獻過一次了。明天再來 —— 寫一段話永遠免費。","quotaMessageFree":"留言永遠免費","quotaAnniversary":"今天是忌日 · 額外包含一次致敬",
 "annivOf":"{name} · 忌日","birthdayOf":"{name} · 生日","upcomingThisMonth":"即將到來","noUpcoming":"未來 30 天沒有忌日或生日"
},
"ru": {
 "exportPdfPoster":"Плакат PDF","exportPdfSub":"A4 / Letter / плакат 2×","exportPng":"Изображение PNG","exportPngSub":"Высокое разрешение, до 4096 px",
 "exportGedcom":"GEDCOM 5.5.1","exportGedcomSub":"Ancestry, Family Tree Maker…","exportJson":"Полная резервная копия (JSON)","exportJsonSub":"Люди, семьи, память",
 "tagFree":"Бесплатно","styleSection":"Стиль","includeLiving":"Включать живых","poster2x":"Размер плаката (2×)","btnExport":"Экспортировать",
 "exportSuccess":"Экспортировано · {name}","exportEmpty":"Пока нечего экспортировать — сначала откройте древо",
 "impResult":"Результат","impPeople":"{count, plural, one{1 человек} few{{count} человека} many{{count} человек} other{{count} человека}}","impFamilies":"{count, plural, one{1 семья} few{{count} семьи} many{{count} семей} other{{count} семьи}} · {generations, plural, one{1 поколение} few{{generations} поколения} many{{generations} поколений} other{{generations} поколения}}",
 "impSkippedTags":"Пропущено неподдерживаемых тегов: {count}","impOpenTree":"Открыть древо","impNewTreePrefix":"Импорт",
 "treesSection":"Семейные древа","newTree":"Новое древо","duplicateTree":"Дублировать","renameTree":"Переименовать","deleteTree":"Удалить древо",
 "currentTag":"Текущее","treeSwitched":"Переключено на {name}","treeCreated":"Древо создано","treeDuplicated":"Древо продублировано","treeDeleted":"Древо удалено","errTreeName":"Введите название",
 "signIn":"Войти","signUp":"Создать аккаунт","email":"Эл. почта","password":"Пароль","passwordHint":"Не менее 6 символов","signOut":"Выйти",
 "authCardTitle":"Синхронизация","authSignedInAs":"Вход: {email}","authNeedAccount":"Создайте бесплатный аккаунт для синхронизации между устройствами. Данные всегда остаются и на этом устройстве.",
 "authSwitchToSignUp":"Впервые здесь? Создать аккаунт","authSwitchToSignIn":"Уже есть аккаунт? Войти",
 "syncNow":"Синхронизировать","allSynced":"Всё синхронизировано","lastSync":"Последняя синхронизация {time}","syncPushed":"Отправлено изменений: {count}","syncPulled":"Получено обновлений: {count}","syncError":"Ошибка синхронизации · проверьте соединение",
 "membersSection":"Члены семьи","copyInvite":"Скопировать ссылку-приглашение","offlineQueueNote":"Изменения в офлайне ждут в очереди и отправятся при подключении.",
 "proFeatSync":"Неограниченная синхронизация и соавторы","proFeatSyncSub":"Бесплатно: 1 синхронизируемое древо","proFeatTribute":"Неограниченные дары","proFeatTributeSub":"Бесплатно: по 1 каждого вида в день",
 "proFeatCandle":"Вечная свеча и премиальные букеты","proFeatCandleSub":"Закреплены вверху страницы памяти","proFeatVoice":"Голосовые сообщения и видео памяти","proFeatVoiceSub":"Слайдшоу с музыкой",
 "proFeatExport":"Экспорт без водяных знаков","proFeatExportSub":"Плакаты PDF, GEDCOM, полная копия","proFeatAds":"Без рекламы","proFeatAdsSub":"В бесплатной версии небольшой баннер",
 "proNote":"Бесплатная версия всегда сохраняет цветы, свечи, благовония и сообщения. Pro добавляет способы помнить — но не продаёт возможность помнить.",
 "proCta":"Продолжить","proBillingNote":"Google Play Billing включится после настройки страницы в магазине.","proPriceSub":"Менее 170 ₽ в месяц · отмена в любой момент",
 "remSameDay":"В тот же день","rem1Day":"За 1 день","rem3Days":"За 3 дня","rem7Days":"За 7 дней","remFreeNote":"Напоминание о годовщине включает один бесплатный дар в этот день.",
 "remTitle":"Напоминания","remAnniv":"Годовщины смерти","remBirth":"Дни рождения","remTime":"Напомнить в","remDays":"За дней",
 "proTitle":"Lararium Pro","syncTitle":"Синхронизация","impPick":"Выберите файл .ged","impNote":"Обработка на устройстве — ничего не загружается","impGo":"Начать импорт",
 "quotaExhaustedTitle":"Дар на сегодня отправлен","quotaExhaustedBody":"Сегодня вы уже поднесли один. Завтра будет больше — а письменное сообщение всегда бесплатно.","quotaMessageFree":"Сообщения всегда бесплатны","quotaAnniversary":"Сегодня годовщина · включён дополнительный дар",
 "annivOf":"{name} · годовщина","birthdayOf":"{name} · день рождения","upcomingThisMonth":"Скоро","noUpcoming":"В ближайшие 30 дней годовщин и дней рождения нет"
},
"nl": {
 "exportPdfPoster":"PDF-poster","exportPdfSub":"A4 / Letter / 2× poster","exportPng":"PNG-afbeelding","exportPngSub":"Hoge resolutie, tot 4096 px",
 "exportGedcom":"GEDCOM 5.5.1","exportGedcomSub":"Ancestry, Family Tree Maker…","exportJson":"Volledige back-up (JSON)","exportJsonSub":"Personen, families, herdenkingen",
 "tagFree":"Gratis","styleSection":"Stijl","includeLiving":"Levende personen opnemen","poster2x":"Posterformaat (2×)","btnExport":"Exporteren",
 "exportSuccess":"Geëxporteerd · {name}","exportEmpty":"Nog niets te exporteren — open eerst de boom",
 "impResult":"Resultaat","impPeople":"{count, plural, one{1 persoon} other{{count} personen}}","impFamilies":"{count, plural, one{1 gezin} other{{count} gezinnen}} · {generations, plural, one{1 generatie} other{{generations} generaties}}",
 "impSkippedTags":"{count} niet-ondersteunde tags overgeslagen","impOpenTree":"Boom openen","impNewTreePrefix":"Geïmporteerd",
 "treesSection":"Stambomen","newTree":"Nieuwe boom","duplicateTree":"Dupliceren","renameTree":"Hernoemen","deleteTree":"Boom verwijderen",
 "currentTag":"Huidig","treeSwitched":"Gewisseld naar {name}","treeCreated":"Boom aangemaakt","treeDuplicated":"Boom gedupliceerd","treeDeleted":"Boom verwijderd","errTreeName":"Voer een naam in",
 "signIn":"Inloggen","signUp":"Account maken","email":"E-mail","password":"Wachtwoord","passwordHint":"Minimaal 6 tekens","signOut":"Uitloggen",
 "authCardTitle":"Synchroniseren","authSignedInAs":"Ingelogd als {email}","authNeedAccount":"Maak een gratis account om tussen apparaten te synchroniseren. Je gegevens blijven altijd ook op dit apparaat.",
 "authSwitchToSignUp":"Nieuw hier? Account maken","authSwitchToSignIn":"Al een account? Inloggen",
 "syncNow":"Nu synchroniseren","allSynced":"Alles gesynchroniseerd","lastSync":"Laatste sync {time}","syncPushed":"{count} wijzigingen geüpload","syncPulled":"{count} updates ontvangen","syncError":"Synchronisatie mislukt · controleer je verbinding",
 "membersSection":"Familieleden","copyInvite":"Uitnodigingslink kopiëren","offlineQueueNote":"Wijzigingen wachten offline en worden verstuurd zodra je weer verbonden bent.",
 "proFeatSync":"Onbeperkt synchroniseren & medewerkers","proFeatSyncSub":"Gratis abonnement: 1 gesynchroniseerde boom","proFeatTribute":"Onbeperkt eerbetoon","proFeatTributeSub":"Gratis abonnement: 1 per dag per soort",
 "proFeatCandle":"Eeuwige kaars & premium boeketten","proFeatCandleSub":"Bovenaan de herdenkingspagina vastgepind","proFeatVoice":"Spraakberichten & herdenkingsvideo","proFeatVoiceSub":"Diavoorstelling met muziek",
 "proFeatExport":"Exports zonder watermerk","proFeatExportSub":"PDF-posters, GEDCOM, volledige back-up","proFeatAds":"Zonder advertenties","proFeatAdsSub":"Het gratis abonnement toont een kleine banner",
 "proNote":"Het gratis abonnement houdt bloemen, kaarsen, wierook en berichten altijd beschikbaar. Pro voegt meer manieren toe om te herdenken — nooit het vermogen om te herdenken.",
 "proCta":"Doorgaan","proBillingNote":"Google Play Billing wordt actief na de store-instelling.","proPriceSub":"Minder dan € 1,67 per maand · op elk moment opzegbaar",
 "remSameDay":"Op de dag zelf","rem1Day":"1 dag","rem3Days":"3 dagen","rem7Days":"7 dagen","remFreeNote":"De jaargetijde-herinnering bevat die dag een gratis eerbetoon.",
 "remTitle":"Herinneringen","remAnniv":"Sterfdagen","remBirth":"Verjaardagen","remTime":"Herinner om","remDays":"Dagen vooraf",
 "proTitle":"Lararium Pro","syncTitle":"Synchroniseren","impPick":"Kies een .ged-bestand","impNote":"Verwerkt op dit apparaat — niets wordt geüpload","impGo":"Importeren starten",
 "quotaExhaustedTitle":"Het eerbetoon van vandaag is verstuurd","quotaExhaustedBody":"Je hebt er vandaag al een aangeboden. Morgen is er weer ruimte — en een geschreven bericht is altijd gratis.","quotaMessageFree":"Berichten zijn altijd gratis","quotaAnniversary":"Jaardag vandaag · een extra eerbetoon inbegrepen",
 "annivOf":"{name} · sterfdag","birthdayOf":"{name} · verjaardag","upcomingThisMonth":"Aankomend","noUpcoming":"Geen sterfdagen of verjaardagen in de komende 30 dagen"
},
}

import os
base = 'lib/l10n'
files = {
 'es':'app_es.arb','pt':'app_pt.arb','fr':'app_fr.arb','de':'app_de.arb','it':'app_it.arb',
 'ja':'app_ja.arb','ko':'app_ko.arb','zh-Hans':'app_zh_Hans.arb','zh-Hant':'app_zh_Hant.arb',
 'ru':'app_ru.arb','nl':'app_nl.arb',
}
for lang, fname in files.items():
    path = os.path.join(base, fname)
    d = json.load(open(path))
    trans = T[lang]
    for k, v in trans.items():
        d[k] = v
    json.dump(d, open(path, 'w'), ensure_ascii=False, indent=2)
    print(f'{fname}: +{len(trans)} keys (total {len(d)})')
print('ALL DONE')
